language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
  - "3.7"
dist: xenial
services:
  - xvfb
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scikit-image tensorflow pyqt keras pytest pytest-cov
  - conda activate test-environment
  - pip install codecov
  - conda remove -q scipy
  - pip install scipy==1.4.1
  - pip install scikit-image
  - pip install tensorflow
  - python setup.py install
script:
    - cat training_data/u-net/network/unetpart* > training_data/u-net/network/currentbest.unet.hdf5
    - xvfb-run -a pytest --cov=./ --cov-report=xml
after_success:
    - codecov
warnings_are_errors: false
